name: Integration tests

on:
  push:
    branches: [ master ]
  schedule:
    - cron: '0 9,19 * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v4
        with:
          java-version: 1.8
      - name: Test
        env:
          MAX_BOTAPI_TOKEN: ${{ secrets.MAX_BOTAPI_TOKEN }}
          MAX_BOTAPI_TOKEN_2: ${{ secrets.MAX_BOTAPI_TOKEN_2 }}
          MAX_BOTAPI_TOKEN_3: ${{ secrets.MAX_BOTAPI_TOKEN_3 }}
          MAX_BOTAPI_MASTER_ID: ${{ secrets.MAX_BOTAPI_MASTER_ID }}
        run: mvn -B test -P stage --file pom.xml